EsercizioU5W1D1/Models/Dipendente.cs
namespace EsercizioU5W1D1.Models
{
    public class Dipendente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Indirizzo { get; set; }
        public string CodiceFiscale { get; set; }
        public bool Sposato { get; set; }
        public int FigliACarico { get; set; }
        public string Mansione { get; set; }

        public Dipendente() { }

        public Dipendente(int id, string nome, string cognome, string indirizzo, string codiceFiscale, bool sposato, int figliACarico, string mansione)
        {
            Id = id;
            Nome = nome;
            Cognome = cognome;
            Indirizzo = indirizzo;
            CodiceFiscale = codiceFiscale;
            Sposato = sposato;
            FigliACarico = figliACarico;
            Mansione = mansione;
        }
    }
}

EsercizioU5W1D1/Models/Pagamento.cs
using System;

namespace EsercizioU5W1D1.Models
{
    public class Pagamento
    {
        public int IdPagamento { get; set; }
        public int IdDipendente { get; set; }
        public double Ammonto { get; set; }
        public string TipoPagamento { get; set; }
        public DateTime DataPagamento { get; set; }

        public Pagamento() { }
        public Pagamento(int idPagamento, int idDipendente, double ammonto, string tipoPagamento, DateTime dataPagamento)
        {
            IdPagamento = idPagamento;
            IdDipendente = idDipendente;
            Ammonto = ammonto;
            TipoPagamento = tipoPagamento;
            DataPagamento = dataPagamento;
        }

    }
}

EsercizioU5W1D1/Controllers/DipendenteController.cs
using EsercizioU5W1D1.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace EsercizioU5W1D1.Controllers
{
    public class DipendenteController : Controller
    {
        List<Dipendente> dipendenti = new List<Dipendente>();
        // GET: Dipendente
        public ActionResult Index()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["Edilizia"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);

            try
            {
                conn.Open();
                string query = "SELECT * FROM Dipendenti";

                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Dipendente dipendente = new Dipendente(
                        Convert.ToInt16(reader["idDipendente"]),
                        reader["nome"].ToString(),
                        reader["cognome"].ToString(),
                        reader["indirizzo"].ToString(),
                        reader["codice_fiscale"].ToString(),
                        Convert.ToBoolean(reader["sposato"]),
                        Convert.ToInt16(reader["n_figli"]),
                        reader["mansione"].ToString()
                        );
                    dipendenti.Add(dipendente);
                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            finally { conn.Close(); }
            return View(dipendenti);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Dipendente dipendente)
        {
            dipendenti.Add(dipendente);

            string connectionString = ConfigurationManager.ConnectionStrings["Edilizia"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);

            try
            {
                conn.Open();
                string query = "INSERT INTO Dipendenti (nome, cognome, indirizzo, codice_fiscale, sposato, n_figli, mansione) " +
                    "VALUES (@nome, @cognome, @indirizzo, @codice_fiscale, @sposato, @n_figli, @mansione)";

                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@nome", dipendente.Nome);
                cmd.Parameters.AddWithValue("@cognome", dipendente.Cognome);
                cmd.Parameters.AddWithValue("@indirizzo", dipendente.Indirizzo);
                cmd.Parameters.AddWithValue("@codice_fiscale", dipendente.CodiceFiscale);
                cmd.Parameters.AddWithValue("@sposato", dipendente.Sposato);
                cmd.Parameters.AddWithValue("@n_figli", dipendente.FigliACarico);
                cmd.Parameters.AddWithValue("@mansione", dipendente.Mansione);

                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            finally { conn.Close(); }

            return View();
        }
    }
}

EsercizioU5W1D1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EsercizioU5W1D1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EsercizioU5W1D1/Controllers/PagamentoController.cs
using EsercizioU5W1D1.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace EsercizioU5W1D1.Controllers
{
    public class PagamentoController : Controller
    {
        List<Pagamento> pagamenti = new List<Pagamento>();
        // GET: Pagamento
        public ActionResult Index()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["Edilizia"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);

            try
            {
                conn.Open();
                string query = "SELECT * FROM Pagamenti";

                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Pagamento pagamento = new Pagamento(
                        Convert.ToInt16(reader["idPagamento"]),
                        Convert.ToInt16(reader["idDipendente"]),
                        Convert.ToDouble(reader["ammonto"]),
                        reader["tipo_pagamento"].ToString(),
                        Convert.ToDateTime(reader["data_pagamento"])
                        );
                    pagamenti.Add(pagamento);
                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            finally { conn.Close(); }
            return View(pagamenti);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Pagamento pagamento)
        {
            pagamenti.Add(pagamento);

            string connectionString = ConfigurationManager.ConnectionStrings["Edilizia"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);

            try
            {
                conn.Open();
                string query = "INSERT INTO Pagamenti (idDipendente, ammonto, tipo_pagamento, data_pagamento) " +
                    "VALUES (@idDipendente, @ammonto, @tipo_pagamento, @data_pagamento)";

                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@idDipendente", pagamento.IdDipendente);
                cmd.Parameters.AddWithValue("@ammonto", pagamento.Ammonto);
                cmd.Parameters.AddWithValue("@tipo_pagamento", pagamento.TipoPagamento);
                cmd.Parameters.AddWithValue("@data_pagamento", pagamento.DataPagamento);

                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            finally { conn.Close(); }

            return View();
        }

    }
}

EsercizioU5W1D1/Views/Dipendente/Create.cshtml
@model EsercizioU5W1D1.Models.Dipendente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dipendente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Indirizzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Indirizzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Indirizzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodiceFiscale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodiceFiscale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodiceFiscale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sposato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Sposato)
                    @Html.ValidationMessageFor(model => model.Sposato, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FigliACarico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FigliACarico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FigliACarico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mansione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mansione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mansione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EsercizioU5W1D1/Views/Dipendente/Index.cshtml
@model IEnumerable<EsercizioU5W1D1.Models.Dipendente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cognome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Indirizzo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodiceFiscale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sposato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FigliACarico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mansione)
        </th>
        <th></th>
    </tr>

@foreach (EsercizioU5W1D1.Models.Dipendente dipendente in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => dipendente.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dipendente.Cognome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dipendente.Indirizzo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dipendente.CodiceFiscale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dipendente.Sposato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dipendente.FigliACarico)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dipendente.Mansione)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

EsercizioU5W1D1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

EsercizioU5W1D1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

EsercizioU5W1D1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <div class="d-flex flex-column justify-content-center align-items-center">
        @Html.ActionLink("Vai alla lista dei dipendenti", "Index", "Dipendente", null, new { @class = "btn btn-primary mb-3" })
        @Html.ActionLink("Vai alla lista dei pagamenti", "Index", "Pagamento", null, new { @class = "btn btn-primary" })
    </div>
</main>

EsercizioU5W1D1/Views/Pagamento/Create.cshtml
@model EsercizioU5W1D1.Models.Pagamento

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pagamento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.IdDipendente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdDipendente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdDipendente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ammonto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ammonto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ammonto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPagamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoPagamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoPagamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataPagamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataPagamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataPagamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EsercizioU5W1D1/Views/Pagamento/Index.cshtml
@model IEnumerable<EsercizioU5W1D1.Models.Pagamento>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdPagamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdDipendente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ammonto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoPagamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataPagamento)
        </th>
        <th></th>
    </tr>

@foreach (EsercizioU5W1D1.Models.Pagamento pagamento in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => pagamento.IdPagamento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => pagamento.IdDipendente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => pagamento.Ammonto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => pagamento.TipoPagamento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => pagamento.DataPagamento)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

EsercizioU5W1D1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nome dell'applicazione", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Informazioni", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contatto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Applicazione ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>